saveWorkspaceProtocol: rolling
savePrefix: ^
linkWorkspacePackages: false
disallowWorkspaceCycles: true
enablePrePostScripts: true
engineStrict: true
publishBranch: main
pmOnFail: download

minimumReleaseAge: 720
minimumReleaseAgeExclude:
  - typebox
  - tfusion
  - vite
  - "@vitejs/*"

packages:
  - "generators/*"
  - "packages/*"
  - "wsbuild"
  - "test"
  - "docs"

allowBuilds:
  "@scarf/scarf": false
  esbuild: false
  msw: true
  vue-demi: false
