minimumReleaseAge: 720

minimumReleaseAgeExclude:
  - typebox
  - tfusion
  - vite

packages:
  - "generators/*"
  - "packages/*"
  - "wsbuild"
  - "test"
  - "docs"

allowBuilds:
  "@scarf/scarf": false
  esbuild: false
  msw: true
